### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by NeilTruongSMC** [google/memcpy-gemm#1]
Hi Kevin, I ran in to a compile error below. Any idea what could be wrong or missing?

#bazel build :memcpy_gemm
INFO: Analyzed target //:memcpy_gemm (38 packages loaded, 1388 targets configured).
INFO: Found 1 target...
ERROR: missing input file '@libnuma//:config.h'
ERROR: /root/.cache/bazel/_bazel_root/0ba465a0ccf81b4aa04a864fc479aa2e/external/libnuma/BUILD:6:1: @libnuma//:numa: missing input file '@libnuma//:config.h'
Target //:memcpy_gemm failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/.cache/bazel/_bazel_root/0ba465a0ccf81b4aa04a864fc479aa2e/external/libnuma/BUILD:6:1 1 input file(s) do not exist
INFO: Elapsed time: 0.605s, Critical Path: 0.04s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by scal444** [comment]
Hi,

Sorry for the late response, don’t check my personal email much during the day, I should link my google email to GitHub, it’s kevinboyd@google.com

My guess is libnuma failed to configure. We wrap autoconf for configuration since libnuma doesn’t yet have a bazel build rule. iirc on vanilla Ubuntu you’d need to install autoconf and maybe one or two other libraries, I’ll add that info to the README.

To debug, can you compile libnuma from source directly? You can see in the bazel build files how we try to do it in memcpy-gemm.

Kevin

**Comment by NeilTruongSMC** [comment]
It was the c++17 requirement. You replied through email. Thx.

I was able to verify the build and able to run the test. Work as expected.

bazel build  --cxxopt='-std=c++17'

**Comment by scal444** [comment]
There is now a .bazelrc file which adds this option by default!
